project:
  type: website
  output-dir: docs

website:
  title: "Piloxita's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Piloxita
      - icon: linkedin
        href: https://www.linkedin.com/in/longlpnguyen/
format:
  html:
    theme: cosmo
    css: styles.css



